/**
 * macOS firewall service - pf (Packet Filter) implementation
 *
 * Configures pf for firewall on macOS.
 * Uses pf instead of the Application Firewall for more control.
 *
 * Note: SSHGuard on macOS uses pf as its backend, so this integrates with it.
 */

import type * as pulumi from "@pulumi/pulumi";
import { runCommand } from "../../lib/command";
import type { FirewallRule, SetupFirewallOptions, SetupFirewallResult } from "./types";
import { DEFAULT_FIREWALL_RULES } from "./types";

/**
 * pf configuration file path
 */
const PF_CONF_PATH = "/etc/pf.anchors/com.syncreeper";

/**
 * Generates pf rules from firewall rules
 */
function generatePfRules(rules: FirewallRule[]): string {
    const lines: string[] = [
        "# SyncReeper pf firewall rules",
        "# Generated by SyncReeper - do not edit manually",
        "",
        "# SSHGuard table for blocked IPs (populated by sshguard)",
        "table <sshguard> persist",
        "",
        "# Block IPs that SSHGuard has flagged",
        "block in quick on egress proto tcp from <sshguard> to any port 22",
        "",
    ];

    for (const rule of rules) {
        const action = rule.action === "allow" ? "pass" : "block";
        const direction = rule.direction;
        const port = rule.port ? `port ${rule.port}` : "";
        const from = rule.from ? `from ${rule.from}` : "";

        // Build the rule
        let pfRule = `${action} ${direction}`;
        if (rule.proto && rule.proto !== "any") {
            pfRule += ` proto ${rule.proto}`;
        }
        if (from) {
            pfRule += ` ${from}`;
        }
        if (port) {
            pfRule += ` to any ${port}`;
        }

        lines.push(`# ${rule.description}`);
        lines.push(pfRule);
        lines.push("");
    }

    return lines.join("\n");
}

/**
 * Sets up pf firewall on macOS
 *
 * This creates pf rules and loads them.
 * The rules integrate with SSHGuard for brute-force protection.
 *
 * Note: Full pf configuration requires admin privileges.
 * For a user-level deployment, we focus on rules that work with SSHGuard.
 */
export function setupFirewallDarwin(options: SetupFirewallOptions = {}): SetupFirewallResult {
    const { rules = DEFAULT_FIREWALL_RULES, dependsOn = [] } = options;
    const resources: pulumi.Resource[] = [];

    // Generate pf rules
    const pfRules = generatePfRules(rules);

    // Write pf anchor file
    // Note: This requires sudo, which is expected for pf configuration
    const writePfAnchor = runCommand({
        name: "write-pf-anchor",
        create: `
            # Create the anchor file
            sudo mkdir -p /etc/pf.anchors
            sudo tee ${PF_CONF_PATH} > /dev/null << 'EOF'
${pfRules}
EOF
            sudo chmod 644 ${PF_CONF_PATH}
            echo "pf anchor file created at ${PF_CONF_PATH}"
        `.trim(),
        delete: `sudo rm -f ${PF_CONF_PATH}`,
        dependsOn,
    });
    resources.push(writePfAnchor);

    // Load the pf anchor
    // We add our anchor to pf.conf if not already present
    const loadPfAnchor = runCommand({
        name: "load-pf-anchor",
        create: `
            # Check if our anchor is already in pf.conf
            if ! grep -q "com.syncreeper" /etc/pf.conf 2>/dev/null; then
                echo 'anchor "com.syncreeper"' | sudo tee -a /etc/pf.conf > /dev/null
                echo 'load anchor "com.syncreeper" from "${PF_CONF_PATH}"' | sudo tee -a /etc/pf.conf > /dev/null
            fi
            
            # Reload pf
            sudo pfctl -f /etc/pf.conf 2>/dev/null || true
            sudo pfctl -e 2>/dev/null || true
            
            echo "pf anchor loaded"
        `.trim(),
        dependsOn: [writePfAnchor],
    });
    resources.push(loadPfAnchor);

    // Verify pf status
    const verifyPf = runCommand({
        name: "verify-pf",
        create: `
            echo "pf status:"
            sudo pfctl -s info 2>/dev/null | head -5 || echo "pf info not available"
            echo ""
            echo "pf rules:"
            sudo pfctl -s rules 2>/dev/null | head -10 || echo "pf rules not available"
            echo ""
            echo "Firewall configured successfully"
        `.trim(),
        dependsOn: [loadPfAnchor],
    });
    resources.push(verifyPf);

    return { resources };
}
